statisticsnorway/dapla-lab-helm-charts-standard-test

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
> Update ssb-project template version

- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
Reverts statisticsnorway/dapla-lab-helm-charts-standard-test#11
> Revert "change volumeMount for VSCode"

- charts/datadoc/Chart.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter/Chart.yaml
- charts/rstudio/Chart.yaml
- charts/vscode-python/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/20)
> Bump library charts

- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/22)
> Update env vars for Jupyter in VSCode

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/25)
> replace pullpolicy

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
locking docker image versions to date because version numbers aren't ready yet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/27)
> lock versions

- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/28)
> add back JUPYTER_PATH in vscode

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/NOTES.txt
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/NOTES.txt
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/NOTES.txt
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/NOTES.txt
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/NOTES.txt
...with norwegian translation. Internal ref https://statistics-norway.atlassian.net/browse/DPSTAT-1007
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/29)
> Update startup text for services

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/NOTES.txt
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/NOTES.txt
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/NOTES.txt
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/NOTES.txt
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/NOTES.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/30)
> Update text formatting

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/32)
> Removed "Extra-bucket" options and moved bucket option at first place

- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/34)
> update XDG_CONFIG_HOME for RStudio

- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/35)
> rstudio fix XDG_CONFIG_HOME

- charts/jupyter-playground/Chart.yaml
- charts/jupyter/Chart.yaml
- charts/rstudio/Chart.yaml
- charts/vscode-python/Chart.yaml
This changes the URL for the "Learn more" button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/37)
> Change 'home page' for services

- charts/jupyter-playground/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/38)
> fix jupyter-playground url

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/39)
> Added "buckets" and "groups" under "dapla"

- .github/workflows/release.yaml
make two more steps run conditionally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/41)
> add more conditional helm-doc generation logic

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/NOTES.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/40)
> Update startup text for Datadoc

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/NOTES.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/42)
> Add notes to datadoc startup

- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/44)
> change user data dir for vscode

- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/46)
> set extensions dir for vscode

- charts/datadoc/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/45)
> Update datadoc home url

- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/47)
> update config path for vscode

- charts/datadoc/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/48)
> Bump helm version to publish Datadoc v1

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/49)
> Modified text for "Dapla tab"

- charts/datadoc/Chart.yaml
- charts/datadoc/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/53)
> Reverted image tag to not introduce possible errors

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/statefulset.yaml
- charts/datadoc/values.schema.json
- charts/datadoc/values.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/52)
> Add new resource sliders

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/56)
> Updated text for tabs 

- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/58)
> bump rstudio image version

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/60)
> Datadoc defaulting to 8Gi memory

- charts/datadoc/Chart.yaml
- charts/datadoc/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/61)
> Added buckets for Datadoc to be able to open datasets

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/62)
> Added Dapla tab to Datadoc to be able to access datasets

- charts/jdemetra/Chart.yaml
- charts/jdemetra/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/65)
> Fix JDemetra image tag

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
Hiding discspace tab and reconfiguring Dapla tab to only show needed values
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/67)
> Changing Dapla tab

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/68)
> Hiding mount buckets as filesystem button

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/69)
> Make jwsacruncher available

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/70)
> fix image versions

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/72)
> Removing mounting of buckets as filesystem in Datadoc

- charts/datadoc/Chart.yaml
- charts/datadoc/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/73)
> Added default group to values.yaml

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/75)
> Another attempt at adding dapla-felles-developers as default value

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
- Removed path from dropdown menu to make it not dependent on activate button
- Moved hidden property to hopefully make the activate button hide
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/78)
> Hide activate button

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
- Moved hidden button code to fix Datadoc config not opening
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/79)
> Moved hiding of button code

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/80)
> Updated versions for images

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
Tested in experimental, this should work as intended now
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/82)
> Hiding the activate data button

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
- charts/datadoc/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/84)
> Update to dataoc v1

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/NOTES.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/85)
> Updated startup text

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/87)
> bump version for rpy2

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/README.md
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/README.md
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/README.md
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/README.md
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/91)
> revert to older image

- charts/jupyter-playground/Chart.yaml
- charts/jupyter/Chart.yaml
- charts/rstudio/Chart.yaml
- charts/vscode-python/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/92)
> bump versions to revert to older image

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/94)
> Remove env variable for PIPX

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/95)
> update jupyter image version

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/96)
> updated image version for all

- charts/datadoc/Chart.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter/Chart.yaml
- charts/rstudio/Chart.yaml
As per: https://github.com/statisticsnorway/dapla-lab-helm-charts-standard-test/pull/97
JIRA ticket: https://statistics-norway.atlassian.net/browse/DPSTAT-1043
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/98)
> update all remaining library-chart refs

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/99)
> bump images

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- Update VSCode iamge version
- bump version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/101)
> update vscode version

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/102)
> update ssb-project-cli version in charts

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/103)
> Bump versions

- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/105)
> bump rstudio version

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/106)
> update image version for vscode

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/108)
> updated image version for testing

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/109)
> Revert image to stable version

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
Bump image versions for jupyter-playground, jupyter, vscode-python and rstudio.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/110)
> Bump image versions

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/112)
> Add PIPX_HOME and PIPX_BIN_DIR for all the images.

- charts/jdemetra/Chart.yaml
Since last publish failed due to branch protection rules
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/114)
> Update JDemtra chart version

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
Add correct pseudo service url to python based services so that `dapla-toolbelt-pseudo` works correctly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/115)
> Add pseudo service url

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/116)
> add autoClosingBrackets in Jupyter

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/118)
> bump vscode version

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
Reverts statisticsnorway/dapla-lab-helm-charts-standard-test#118
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/119)
> Revert "bump vscode version"

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/120)
> push new vscode build

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/124)
> bump version to fix r dependencies and set mem limit

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/126)
> add mem_limit env var

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/127)
> 'MEM_LIMIT' env variable uses memory limits

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
new image versions contain new anywidget python
library
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/129)
> vscode-python: new image version

- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/131)
> jupyter: add statbankEncryptUrl as envvar

- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
envvar which shows the currently logged in dapla user's email address
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/132)
> jupyter: add DAPLA_USER envvar

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/133)
> Add common envvars to remaining services

- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/134)
> rstudio: update image versions

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
adds system dependencies for installing 'fellesr' R package
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/135)
> jupyter: update to latest image

- charts/jupyter-pyspark/.helmignore
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/README.md
- charts/jupyter-pyspark/templates/NOTES.txt
- charts/jupyter-pyspark/templates/configmap-oauth2proxy.yaml
- charts/jupyter-pyspark/templates/configmap-repository.yaml
- charts/jupyter-pyspark/templates/networkpolicy-ingress.yaml
- charts/jupyter-pyspark/templates/networkpolicy.yaml
- charts/jupyter-pyspark/templates/pvc.yaml
- charts/jupyter-pyspark/templates/role-binding.yaml
- charts/jupyter-pyspark/templates/secret-git.yaml
- charts/jupyter-pyspark/templates/secret-oidc.yaml
- charts/jupyter-pyspark/templates/service.yaml
- charts/jupyter-pyspark/templates/serviceaccount.yaml
- charts/jupyter-pyspark/templates/serviceentry.yaml
- charts/jupyter-pyspark/templates/simpleproxyclient.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/templates/tests/test-connection.yaml
- charts/jupyter-pyspark/templates/virtualservice.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/136)
> add jupyter-pyspark

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/137)
> rename image prefix

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/138)
> bump docker image version

- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/139)
> Add support for SSBucketeer reason and duration request

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
also remove old cruft like `x-form` which is no longer used by onyxia
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/140)
> vscode-python: update schema to support onyxia v9

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/141)
> Support data admins ssbucketeer

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/144)
> Fixup jupyter onyxia v9 migration typo

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/145)
> jupyter-playground: migrate to onyxia v9

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/146)
> Update jupyter-pyspark to work on v9

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
Duration is only relevant when starting as a group which requires a reason, so we hide it when it is irrelevant
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/148)
> Hide duration field when reason is empty

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/147)
> Upgrade Datadoc from Oxyxia v8 to v9

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
fixup the dapla buckets enabled path in requestedDuration field which caused errors when launching services:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/150)
> fixup requestedDuration field

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/151)
> Correctly hide duration field when reason is empty

- charts/datadoc/Chart.yaml
- charts/datadoc/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/154)
> Added maintained by team-metadata to get logs

- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/156)
> rstudio: upgrade chart to onyxia-v9

- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/157)
> rstudio: forgot to add startupProbe

- charts/vscode-python/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/159)
> Bump version

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/161)
> vscode-python: fixup

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/162)
> Fixup vscode python

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/164)
> bump jupyter-pyspark images

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/165)
> Change auth type jupyter-pyspark

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/166)
> Changing path to json schemas

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
Change network-policy and tolerations and added diskplass instead of  persistence
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/167)
> Fix schema paths Datadoc

- charts/vscode-python/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/168)
> Revert vscode-python to V9

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/169)
> revert changes to working vscode configuration

- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
make envvar environment (prod, test, dev) dependent
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/170)
> vscode-python: change statbank-base-url

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/172)
> update statbank base URL in rest of services

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/173)
> Introduce cpu variable

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
- flake.lock
- flake.nix
update services to use the new dapla V10 schema for dapla related settings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/176)
> Make services use new dapla schema

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/178)
> Bump spark version for updates jars

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/180)
> Use new jupyter-pyspark image

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/181)
> trying to fix spark startup

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
internal ref: https://statistics-norway.atlassian.net/browse/DPSTAT-1146
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/183)
> update 'tjeneste' config in all our services

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/184)
> Updating schema for Datadoc on Onyxia v10

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/187)
> Diskplass tab changes

- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jdemetra/values.schema.json
- charts/jdemetra/values.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
Internal ref: https://statistics-norway.atlassian.net/browse/DPSTAT-1147
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/188)
> Update resources settings

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/190)
> quote annotations in all IDE services

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/statefulset.yaml
- charts/datadoc/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/191)
> Updating statefulset for Datadoc

- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jdemetra/values.schema.json
- charts/jdemetra/values.yaml
specifically the 'data' and 'tjeneste' settings accordions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/194)
> jdemetra: update inline with other charts on onyxia v10

- charts/jdemetra/Chart.yaml
- charts/jdemetra/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/196)
> fixup 'versjon' text in settings

- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jdemetra/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/197)
> jdemetra: fix bucket mounting

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/198)
> pass jupyter lab command through spark init script

- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/201)
> Fix subpath->subPath in jupyter work volumeMount

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/statefulset.yaml
- charts/datadoc/values.schema.json
- charts/datadoc/values.yaml
- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jdemetra/values.schema.json
- charts/jdemetra/values.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/203)
> Add advanced tab for all services

- charts/jupyter/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/204)
> bump lib chart for upstream-timeout changes

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/rstudio/Chart.yaml
- charts/vscode-python/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/205)
> update lib chart for services

- charts/jdemetra/Chart.yaml
- charts/jdemetra/values.schema.json
Reverts statisticsnorway/dapla-lab-helm-charts-standard-test#207
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/208)
> Revert "hide diskplass and resources for jdemetra"

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/209)
> bump jupyterlab version

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/211)
> bump vscode for extensions

- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/215)
> bump vscode

- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jdemetra/values.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/217)
> Add configuration for mounting shared bucket

- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/219)
> update rstudio image

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/220)
> Update image versions of VSCode and Jupyter

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
- **fixup: Add new versions to values.yaml**
- **bump jupyter chart**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/221)
> fixup: Add new versions to values.yaml

- charts/jdemetra/Chart.yaml
- charts/jdemetra/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/222)
> hide resources and disk tab

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/226)
> remove overwritedefaultwith for statbanktest

- charts/jupyter/Chart.yaml
- charts/jupyter/templates/poddisruptionbudget.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/228)
> add podDisruptionBudget for jupyter

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/233)
> bump versions to add tmux

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/236)
> Fix MEM_LIMIT to match actual limit for jupyter services

- charts/qgis/.helmignore
- charts/qgis/Chart.yaml
- charts/qgis/README.md
- charts/qgis/templates/NOTES.txt
- charts/qgis/templates/configmap-oauth2proxy.yaml
- charts/qgis/templates/configmap-repository.yaml
- charts/qgis/templates/networkpolicy-ingress.yaml
- charts/qgis/templates/networkpolicy.yaml
- charts/qgis/templates/poddisruptionbudget.yaml
- charts/qgis/templates/pvc.yaml
- charts/qgis/templates/role-binding.yaml
- charts/qgis/templates/secret-git.yaml
- charts/qgis/templates/secret-oidc.yaml
- charts/qgis/templates/service.yaml
- charts/qgis/templates/serviceaccount.yaml
- charts/qgis/templates/serviceentry.yaml
- charts/qgis/templates/simpleproxyclient.yaml
- charts/qgis/templates/statefulset.yaml
- charts/qgis/templates/tests/test-connection.yaml
- charts/qgis/templates/virtualservice.yaml
- charts/qgis/values.schema.json
- charts/qgis/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/237)
> QGIS config init

- charts/qgis/Chart.yaml
- charts/qgis/templates/statefulset.yaml
- charts/qgis/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/238)
> qgis-update-start-args

- charts/qgis/Chart.yaml
- charts/qgis/README.md
- charts/qgis/values.schema.json
- charts/qgis/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/239)
> Qgis change port

- charts/qgis/Chart.yaml
- charts/qgis/values.schema.json
- charts/qgis/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/240)
> bump qgis version

- charts/qgis/Chart.yaml
- charts/qgis/values.schema.json
- charts/qgis/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/242)
> add window title

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/244)
> bump library-chart-and-image-for-jupyter

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/245)
> Jupyter testing ssb project build

- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/qgis/Chart.yaml
- charts/qgis/values.schema.json
- charts/qgis/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/246)
> bump jupyter and qgis

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/247)
> add ssb-project build support for all applications

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/statefulset.yaml
- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
library chart with newest additions: node affinity for node pool selection, and upgrade oauth2proxy
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/249)
> Node affinity  and mics

- charts/datadoc/Chart.yaml
- charts/datadoc/templates/statefulset.yaml
- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
The library chart expect the values without suffixes
internal ref: [DPSKY-997]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/250)
[DPSKY-997]: https://statistics-norway.atlassian.net/browse/DPSKY-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix suffix of resources

- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/251)
> dont use schema for gitconfig for rstudio

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
- charts/jdemetra/Chart.yaml
- charts/jdemetra/values.schema.json
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vardef-forvaltning/Chart.yaml
- charts/vardef-forvaltning/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
Such that we can provide two hostnames in a migration periode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/257)
> feat(ingress): Add support for extra hostname

- charts/datadoc/Chart.yaml
- charts/datadoc/values.schema.json
- charts/jdemetra/Chart.yaml
- charts/jdemetra/values.schema.json
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/vardef-forvaltning/Chart.yaml
- charts/vardef-forvaltning/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/261)
> fix: overwriteSchemaWith should be inside x-onyxia configuration

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/265)
> Update Spark version

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/266)
> Fix default Spark version

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter/Chart.yaml
- charts/vscode-python/Chart.yaml
Fixup error from the previous PR where some chart versions weren't bumped
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/269)
> bump chart versions

- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/272)
> move images from west4 to north1

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/templates/statefulset.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/273)
> change west4 to north1

- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/274)
> change start image

- charts/jdemetra/Chart.yaml
- charts/jdemetra/templates/statefulset.yaml
- charts/jdemetra/values.schema.json
- charts/jdemetra/values.yaml
- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/templates/statefulset.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/templates/statefulset.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vscode-python/Chart.yaml
- charts/vscode-python/templates/statefulset.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/281)
> Support personal startupscript

- charts/vardef-forvaltning/Chart.yaml
- charts/vardef-forvaltning/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/282)
> Vardef - use jupyter image from north1

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter-pyspark/Chart.yaml
- charts/jupyter-pyspark/values.schema.json
- charts/jupyter-pyspark/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
- charts/rstudio/Chart.yaml
- charts/rstudio/values.schema.json
- charts/rstudio/values.yaml
- charts/vardef-forvaltning/Chart.yaml
- charts/vardef-forvaltning/values.schema.json
- charts/vscode-python/Chart.yaml
- charts/vscode-python/values.schema.json
- charts/vscode-python/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/284)
> bump images and modify vardefs default startscript value

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/289)
> Bump jupyter images to add jupytergis

- charts/jupyter-playground/Chart.yaml
- charts/jupyter-playground/values.schema.json
- charts/jupyter-playground/values.yaml
- charts/jupyter/Chart.yaml
- charts/jupyter/values.schema.json
- charts/jupyter/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/291)
> Update jupyter and jupyterplayground

- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/311)
> fix timeout bug string->int

- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/312)
> add startupProbe rstudio

- charts/rstudio/Chart.yaml
- charts/rstudio/templates/statefulset.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-lab-helm-charts-standard-test/315)
> set timeout to 30 min for rstudio
